# fly.toml app configuration file generated for empty-fog-1619 on 2023-05-07T21:44:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-fog-1619"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
